Repository suisei-cn/starbuttons, pull requests merged in 2020-06, with the labels that each got.

#51 fix: unable to display text on buttons
  src/views/MainView.vue
Labels: bug

#53 Add 5 sounds from lwszUzu_ARc
  public/assets/aaaaaaaaaaakuso.mp3
  public/assets/dancemama.mp3
  public/assets/wuwawuwawuwa.mp3
  public/assets/yameru.mp3
  public/assets/yiaaaaaaaaaaaa.mp3
  public/sounds.json
Labels: new-sound

#54 feat(a11y): Use a brighter background color for focus
  src/style/colorScheme.scss
  src/style/style.scss
Labels: a11y
